src/main/java/info/stieghorst/tasklist/jsf/model/Status.java
package info.stieghorst.tasklist.jsf.model;

public enum Status {
	OPEN, FINISHED, SCHEDULED, MIGRATED;
	
	public static char printSymbol(Status stat) {
		char symbol = '?';
		if (stat == Status.OPEN) {
			symbol = '\u26aa';
		}
		else if(stat == Status.FINISHED) {
			symbol = '\u2714';
		}
		else if(stat == Status.SCHEDULED) {
			symbol = '►';
		}
		else if (stat == Status.MIGRATED) {
			symbol = '◄';
		}
		return symbol;
	}
}

src/main/java/info/stieghorst/tasklist/jsf/model/Task.java
package info.stieghorst.tasklist.jsf.model;

import java.io.Serializable;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Logger;

import info.stieghorst.tasklist.jsf.util.TaskHelper;


/**
 * The persistent class for the task database table.
 * 
 */
public class Task implements Serializable {
	private static final long serialVersionUID = 1L;

	private Logger logger = Logger.getLogger(this.getClass().getName());
	
	private int id;

	private String description;

	private Status status;
	
	private LocalDate dueDate;
	
	private Date taskDate;

	private TimeUnit timeUnit;

	public Task() {
		logger.info("default constructor");
	}
	
	public Task(String description, LocalDate dueDate, TimeUnit timeUnit) {
		logger.info("constructor - 3 Argumente");
		this.description = description;
		this.dueDate = dueDate;
		this.timeUnit = timeUnit;
		this.status = Status.OPEN;
	}


	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	public String getDescription() {
		return description;
	}


	public void setDescription(String description) {
		this.description = description;
	}


	public Status getStatus() {
		return status;
	}


	public void setStatus(Status status) {
		this.status = status;
	}
	
	public char getStatusSymbol() {
		return Status.printSymbol(status);
	}


	public LocalDate getDueDate() {
		return dueDate;
	}


	public void setDueDate(LocalDate dueDate) {
		this.dueDate = dueDate;
		if(dueDate == null) {
			this.taskDate = null;
		}
		else {
			this.taskDate = Date.from(dueDate.atStartOfDay(ZoneId.systemDefault()).toInstant());
		}
	}
	
	public Date getTaskDate() {
		return taskDate;
	}

	public void setTaskDate(Date taskDate) {
		this.taskDate = taskDate;
		if(taskDate == null) {
			this.dueDate = null;
		}
		else {
			this.dueDate = Instant.ofEpochMilli(taskDate.getTime()).atZone(ZoneId.systemDefault()).toLocalDate();
		}
	}
	
	public String getDateAsString() {
		if(dueDate == null) {
			return "";
		}
		else {
			DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEE, dd.MM.yyyy");
			return dueDate.format(formatter);
		}
	}
	
	public String getTimeUnitAndDate() {
		return TaskHelper.createTitleString(dueDate, timeUnit);
	}

	public TimeUnit getTimeUnit() {
		return timeUnit;
	}


	public void setTimeUnit(TimeUnit timeUnit) {
		this.timeUnit = timeUnit;
	}
	
	public boolean isUpdateAble() {
		return this.status.equals(Status.OPEN) || this.status.equals(Status.MIGRATED);
	}

	public boolean isReadOnly() {
		return this.status.equals(Status.SCHEDULED) || this.status.equals(Status.FINISHED);
	}

	@Override
	public String toString() {
		return "Task: " + id + "|" + description + "|" + status + "|" + dueDate
				+ "|" + timeUnit;
	}
	

}

src/main/java/info/stieghorst/tasklist/jsf/model/TimeUnit.java
package info.stieghorst.tasklist.jsf.model;

public enum TimeUnit {
	DAY, WEEK, MONTH, YEAR, NONE;

}

src/main/java/info/stieghorst/tasklist/jsf/controller/ListController.java
package info.stieghorst.tasklist.jsf.controller;

import java.time.LocalDate;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import info.stieghorst.tasklist.jsf.model.Status;
import info.stieghorst.tasklist.jsf.model.Task;
import info.stieghorst.tasklist.jsf.model.TimeUnit;
import info.stieghorst.tasklist.jsf.service.TaskListService;
import info.stieghorst.tasklist.jsf.service.TaskListServiceImpl;
import info.stieghorst.tasklist.jsf.util.TaskHelper;

@ManagedBean
@SessionScoped
public class ListController {
	
	Logger logger = Logger.getLogger(this.getClass().getName());
	
	private LocalDate selectedDate;
	private TimeUnit timeUnit;
	
	private Map<String, TimeUnit> timeUnitMap;
	
	private Map<Character, Status> statusMap;
	
	private TaskListService service;
	
	private List<Task> currentTaskList;
	
	private Task currentTask;
	
	private String errorMessage;
	
	public ListController() throws Exception {
		service = new TaskListServiceImpl();

		selectedDate = LocalDate.now();
		timeUnit = TimeUnit.DAY;
		
		timeUnitMap = new LinkedHashMap<>();
		timeUnitMap.put("Tag", TimeUnit.DAY);
		timeUnitMap.put("Woche", TimeUnit.WEEK);
		timeUnitMap.put("Monat", TimeUnit.MONTH);
		timeUnitMap.put("Jahr", TimeUnit.YEAR);
		timeUnitMap.put("-ohne-", TimeUnit.NONE);
		
		statusMap = new LinkedHashMap<>();
		statusMap.put(Status.printSymbol(Status.OPEN), Status.OPEN);
		statusMap.put(Status.printSymbol(Status.FINISHED), Status.FINISHED);
		statusMap.put(Status.printSymbol(Status.SCHEDULED), Status.SCHEDULED);
		statusMap.put(Status.printSymbol(Status.MIGRATED), Status.MIGRATED);
	}
	
	public String getDateTitle() {
		return TaskHelper.createTitleString(selectedDate, timeUnit);
	}

	public LocalDate getSelectedDate() {
		return selectedDate;
	}

	public void setSelectedDate(LocalDate selectedDate) {
		this.selectedDate = selectedDate;
	}

	public TimeUnit getTimeUnit() {
		return timeUnit;
	}

	public void setTimeUnit(TimeUnit timeUnit) {
		this.timeUnit = timeUnit;
	}
	
	public List<Task> getCurrentTaskList() {
		return currentTaskList;
	}
	
	public Task getCurrentTask() {
		return currentTask;
	}

	public void setCurrentTask(Task currentTask) {
		this.currentTask = currentTask;
	}

	public Map<String, TimeUnit> getTimeUnitMap() {
		return timeUnitMap;
	}

	public String getErrorMessage() {
		return errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	public void loadTasklist() throws Exception {
		logger.info("loadTasklist()");
		currentTaskList = service.getTaskList(selectedDate, timeUnit);
	}

	public String newListForTimeUnit(String input) {
		logger.info("newListForTimeUnit(" + input + ")");
		timeUnit = TaskHelper.convertTimeUnitFromString(input);
		selectedDate = LocalDate.now();
		selectedDate = TaskHelper.calcCorrectDate(selectedDate, timeUnit);

		try {
			loadTasklist();
		} catch (Exception e) {
			errorMessage = e.getLocalizedMessage();
			return "error";
		}
		
		return "tasklist?faces-redirect=true";
	}
	
	public String newListForMove(String input) {
		logger.info("newListForMove(" + input + ")");
		int move = 0;
		if(input.equals("next")) {
			move = 1;
		}
		else if(input.equals("previous")) {
			move = -1;
		}
		else {
			move = 0;
		}
		selectedDate = TaskHelper.calcDateForRequestedPage(selectedDate, move, timeUnit);
		logger.info("newListForMove() - selectedDate = " + selectedDate);
		
		try {
			loadTasklist();
		} catch (Exception e) {
			errorMessage = e.getLocalizedMessage();
			return "error";
		}
		
		return "tasklist?faces-redirect=true";
	}
	
	public String showNewTaskForm() {
		logger.info("showNewTaskForm()");
		currentTask = new Task();
		currentTask.setDueDate(LocalDate.now());
		currentTask.setTimeUnit(TimeUnit.NONE);
		currentTask.setStatus(Status.OPEN);
		return "add-task-form";
	}
	
	public String addNewTask() {
		logger.info("addNewTask()");
		LocalDate correctedDate = TaskHelper.calcCorrectDate(
				currentTask.getDueDate(), currentTask.getTimeUnit());
		currentTask.setDueDate(correctedDate);

		try {
			service.addTask(currentTask);
		} catch (Exception e) {
			errorMessage = e.getLocalizedMessage();
			return "error";
		}
		
		return "tasklist?faces-redirect=true";
	}
	
	public String showUpdateForm(int id) {
		logger.info("showUpdateForm(" + id + ")");
		Task tempTask = null;

		try {
			tempTask = service.getTaskById(id);
		} catch (Exception e) {
			errorMessage = e.getLocalizedMessage();
			return "error";
		}
		
		if(tempTask == null) {
			logger.info("getTaskByID returned NULL!!!");
		}
		else {
			currentTask = tempTask;
			logger.info("currentTask: \n" + currentTask);
		}
		
		return "update-task-form";
	}
	
	public String updateTask() {
		logger.info("updateTask()");

		try {
			service.updateTask(currentTask);
		} catch (Exception e) {
			errorMessage = e.getLocalizedMessage();
			return "error";
		}
		
		return "tasklist?faces-redirect=true";
	}
	
	public String postponeTask(int id) {
		logger.info("postponeTask(" + id + ")");

		try {
			service.postponeTask(id);
		} catch (Exception e) {
			errorMessage = e.getLocalizedMessage();
			return "error";
		}
		
		return "tasklist?faces-redirect=true";
		
	}
	
	public String finishTask(int id) {
		logger.info("finishTask(" + id + ")");

		try {
			service.finishTask(id);
		} catch (Exception e) {
			errorMessage = e.getLocalizedMessage();
			return "error";
		}
		
		return "tasklist?faces-redirect=true";
	}

}

src/main/webapp/add-task-form.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<title>Neue Aufgabe</title>
	
	<h:outputStylesheet library="css" name="style.css"  />
	<h:outputStylesheet library="css" name="add-task-style.css"  />
	
	<script>
		PrimeFaces.locales ['de'] = {
		    closeText: 'Schließen',
		    prevText: 'Zurück',
		    nextText: 'Weiter',
		    monthNames: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember' ],
		    monthNamesShort: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez' ],
		    dayNames: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
		    dayNamesShort: ['Son', 'Mon', 'Die', 'Mit', 'Don', 'Fre', 'Sam'],
		    dayNamesMin: ['S', 'M', 'D', 'M ', 'D', 'F ', 'S'],
		    weekHeader: 'Woche',
		    firstDay: 1,
		    isRTL: false,
		    showMonthAfterYear: false,
		    yearSuffix:'',
		    timeOnlyTitle: 'Nur Zeit',
		    timeText: 'Zeit',
		    hourText: 'Stunde',
		    minuteText: 'Minute',
		    secondText: 'Sekunde',
		    currentText: 'Aktuelles Datum',
		    ampm: false,
		    month: 'Monat',
		    week: 'Woche',
		    day: 'Tag',
		    allDayText: 'Ganzer Tag'
		};
	</script>
	
</h:head>

<h:body>

	<div id="wrapper">
		<div id="header">
			<h2>Aufgabenliste</h2>
		</div>
	</div>
	
	<div id="container">
		<h3>Neue Aufgabe</h3>

		<p:messages globalOnly="true" />

		<h:form id="form" style="margin-top: 10px;" >
			<p:panelGrid columns="3" styleClass="ui-noborder">
			
				<p:outputLabel>Beschreibung:</p:outputLabel>
				<p:inputText value="#{listController.currentTask.description}" id="description" size="60"/> 
				<p:message for="description" />
	
				<p:outputLabel>Zeiteinheit:</p:outputLabel> 
				<p:selectOneMenu value="#{listController.currentTask.timeUnit}" id="timeUnit">
					<f:selectItems value="#{listController.timeUnitMap}" />
				</p:selectOneMenu>
				<p:message for="timeUnit" />
				
				<p:outputLabel>Datum:</p:outputLabel> 
				<p:calendar value="#{listController.currentTask.taskDate}" id="taskDate" mode="inline" locale="de"/>
				<p:message for="taskDate" />
	
				<p:outputLabel /> 
				<p:commandButton value="Speichern" styleClass="save" action="#{listController.addNewTask}"/>
			
			</p:panelGrid>
		</h:form>

		<div style="clear: both;"></div>

		<p><h:outputLink value="tasklist.xhtml">Zurück zur Liste</h:outputLink></p>

	</div>	
</h:body>
</html>

src/main/webapp/error.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<title>Aufgabenliste -- Fehler</title>
	
	<h:outputStylesheet library="css" name="style.css"  />
	<h:outputStylesheet library="css" name="add-task-style.css"  />
	
</h:head>

<h:body>
<h:form>
	<div id="wrapper">
		<div id="header">
			<h2>Aufgabenliste - Fehler</h2>
		</div>
	</div>
	
	<div id="container">
		<h3>Hier hat es einen Fehler gegeben!</h3>
		<p>#{listController.errorMessage}</p>
		<p><h:outputLink value="tasklist.xhtml">Zurück zur Liste</h:outputLink></p>
	</div>	
</h:form>
</h:body>
</html>

src/main/webapp/tasklist.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<f:metadata>
  <f:event type="preRenderView" listener="#{listController.loadTasklist()}"/>
</f:metadata>

<h:head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<title>Aufgabenliste</title>
	
	<h:outputStylesheet library="css" name="style.css"  />
	
</h:head>

<h:body>
<h:form>

	<div id="wrapper">
		<div id="header">
			<h2>Aufgabenliste - #{listController.dateTitle}</h2>
		</div>
		<div id="menu">
			<p:commandLink action="#{listController.showNewTaskForm}">neue Aufgabe</p:commandLink> || 
			Zeiteinheit: 
			<p:commandLink action="#{listController.newListForTimeUnit('day')}">Tag</p:commandLink> |
			<p:commandLink action="#{listController.newListForTimeUnit('week')}">Woche</p:commandLink> |
			<p:commandLink action="#{listController.newListForTimeUnit('month')}">Monat</p:commandLink> |
			<p:commandLink action="#{listController.newListForTimeUnit('year')}">Jahr</p:commandLink> |
			<p:commandLink action="#{listController.newListForTimeUnit('none')}">ohne</p:commandLink> |
			<p:commandLink action="#{listController.newListForMove('previous')}">&lt; (zurück)</p:commandLink> |
			<p:commandLink action="#{listController.newListForMove('next')}">&gt; (vor)</p:commandLink>
		</div>
	</div>

	<div id="container">

		<div id="content">
		
			<p:dataTable value="#{listController.currentTaskList}" var="task"
				styleClass="demo-table" 
				headerClass="demo-table-header"
				rowClasses="demo-table-odd-row,demo-table-even-row">

				<p:column width="60" style="center">
					<f:facet name="header">Status</f:facet>
					<div style="text-align:center">
						<h:outputText value="#{task.statusSymbol}" id="statSymbol" />
						<p:tooltip for="statSymbol" value="#{task.status}" />
					</div>
				</p:column>

				<p:column>
					<f:facet name="header">Beschreibung</f:facet>
					#{task.description}
				</p:column>

				<p:column width="280">
					<f:facet name="header">Zeitraum</f:facet>
					#{task.timeUnitAndDate}
				</p:column>

				<p:column width="140" >
					<f:facet name="header">Aktion</f:facet>
					<p:commandLink id="closeTask" value="&#x2714;" rendered="#{task.updateAble}" action="#{listController.finishTask(task.id)}"/>
					<p:tooltip for="closeTask" value="Aufgabe erledigt" /> 
					<h:outputText rendered="#{task.updateAble}" value=" | " />
					<p:commandLink id="postpone" value="&#x25ba;" rendered="#{task.updateAble}" action="#{listController.postponeTask(task.id)}"/>
					<p:tooltip for="postpone" value="Aufgabe verschieben" />  
					<h:outputText rendered="#{task.updateAble}" value=" | " />
					<p:commandLink id="changeTask" value="Ändern" rendered="#{task.updateAble}" action="#{listController.showUpdateForm(task.id)}"/>
					<p:tooltip for="changeTask" value="Aufgabe bearbeiten" />
				</p:column>

			</p:dataTable>
						

		</div>
		
	</div>

</h:form>
</h:body>
</html>

src/main/webapp/update-task-form.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<title>Aufgabe ändern</title>
	
	<h:outputStylesheet library="css" name="style.css"  />
	<h:outputStylesheet library="css" name="add-task-style.css"  />
	
	<script>
		PrimeFaces.locales ['de'] = {
		    closeText: 'Schließen',
		    prevText: 'Zurück',
		    nextText: 'Weiter',
		    monthNames: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember' ],
		    monthNamesShort: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez' ],
		    dayNames: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
		    dayNamesShort: ['Son', 'Mon', 'Die', 'Mit', 'Don', 'Fre', 'Sam'],
		    dayNamesMin: ['S', 'M', 'D', 'M ', 'D', 'F ', 'S'],
		    weekHeader: 'Woche',
		    firstDay: 1,
		    isRTL: false,
		    showMonthAfterYear: false,
		    yearSuffix:'',
		    timeOnlyTitle: 'Nur Zeit',
		    timeText: 'Zeit',
		    hourText: 'Stunde',
		    minuteText: 'Minute',
		    secondText: 'Sekunde',
		    currentText: 'Aktuelles Datum',
		    ampm: false,
		    month: 'Monat',
		    week: 'Woche',
		    day: 'Tag',
		    allDayText: 'Ganzer Tag'
		};
	</script>
	
</h:head>

<h:body>

	<div id="wrapper">
		<div id="header">
			<h2>Aufgabenliste</h2>
		</div>
	</div>
	
	<div id="container">
		<p:messages globalOnly="true" />

		<h:form id="form" style="margin-top: 10px;" >
			<p:panelGrid columns="3" styleClass="ui-noborder">
			
				<f:facet name="header">Aufgabe ändern</f:facet>
			
				<p:outputLabel>Beschreibung:</p:outputLabel>
				<p:inputText value="#{listController.currentTask.description}" id="description"/> 
				<p:message for="description" />
	
				<p:outputLabel>Datum:</p:outputLabel> 
				<p:calendar value="#{listController.currentTask.taskDate}" id="taskDate" mode="inline" locale="de"/>
				<p:message for="taskDate" />
	
				<p:outputLabel>Zeiteinheit:</p:outputLabel> 
				<p:selectOneMenu value="#{listController.currentTask.timeUnit}" id="timeUnit">
					<f:selectItems value="#{listController.timeUnitMap}" />
				</p:selectOneMenu>
				<p:message for="timeUnit" />
				
				<f:facet name="footer"> 
					<p:commandButton value="Speichern" icon="ui-icon-check" action="#{listController.updateTask}"/>
				</f:facet>
			
			</p:panelGrid>
		</h:form>

		<div style="clear: both;"></div>

		<p><h:outputLink value="tasklist.xhtml">Zurück zur Liste</h:outputLink></p>

	</div>	
</h:body>
</html>